// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXJzC9h6UiqlWBPrmyc4yIL8CPCrSqbVw',
    appId: '1:874415662622:web:medipolapp',
    messagingSenderId: '874415662622',
    projectId: 'medipolapp-e3b4f',
    authDomain: 'medipolapp-e3b4f.firebaseapp.com',
    storageBucket: 'medipolapp-e3b4f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXJzC9h6UiqlWBPrmyc4yIL8CPCrSqbVw',
    appId: '1:874415662622:android:f3de208f88227600a0f00f',
    messagingSenderId: '874415662622',
    projectId: 'medipolapp-e3b4f',
    storageBucket: 'medipolapp-e3b4f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWta8PM5Q1znNLppnS0Ac4dYLb9wHhkhA',
    appId: '1:874415662622:ios:fbe620970b6f9007a0f00f',
    messagingSenderId: '874415662622',
    projectId: 'medipolapp-e3b4f',
    storageBucket: 'medipolapp-e3b4f.firebasestorage.app',
    iosBundleId: 'com.example.medipolapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWta8PM5Q1znNLppnS0Ac4dYLb9wHhkhA',
    appId: '1:874415662622:ios:fbe620970b6f9007a0f00f',
    messagingSenderId: '874415662622',
    projectId: 'medipolapp-e3b4f',
    storageBucket: 'medipolapp-e3b4f.firebasestorage.app',
    iosBundleId: 'com.example.medipolapp',
  );
}
